import Head from "next/head";
import Image from "next/image";
import Fileupload from "../src/component/Fileupload";
import styles from "../styles/Home.module.css";

export default function Home() {
  function onFileupload(data) {
    console.log(JSON.stringify(data));
    const response = fetch("/api/uploadFile", {
      body: data,
      method: "POST",
    });
    console.log(response);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>NFC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Fileupload onChange={onFileupload} name="trash" />
      </main>
    </div>
  );
}
